### ISSUE TITLE
[Documentation respectively Question] Screenshots and GUIs?

### ISSUE THREAD

**Issue by rubyFeedback** [sbagdat/mastermind_generator#1]
Hey there,

Could you add a screenshot how to use it e. g. if on the commandline?

Is there any GUI, be it ruby-gtk, www-usage or anything like that?

Right now I am not sure what the game is. I know one mastermind game:

https://i.imgur.com/0Qrr3Y6.jpg

But I am not sure whether it is the same, hence why I ask here. :)

**Comment by sbagdat** [comment]
Hey @rubyFeedback,

Thanks for the feedback! It is a mastermind game **generator**, not an actual game. By using it, you can create classic mastermind game like at your image, also you can customize items (if you don't like the colors), add difficulty levels, timers, etc. So you can use it from command line, web, or inside a gui.

I have already put a demo folder inside the repo and mentioned about it in the readme file. You can test it by cloning the repo to your local machine, then when inside the repo folder, just run `ruby ./demo/lib/mastermind.rb` and play the game (full code is in /demo folder).
